Repository sozign/codeit-top-secret-X, pull requests merged in 2024-01, with the labels that each got.

#12 style: tailwind config 폰트추가, 컬러픽 사용성 개선
  src/styles/globals.css
  tailwind.config.ts
Labels: style

#15 design: breakpoint 지정
  src/pages/index.tsx
  tailwind.config.ts
Labels: design

#19 feat: page 디렉토리 구조 세팅
  src/pages/dashboard/[boardid]/edit.tsx
  src/pages/dashboard/[boardid]/index.tsx
  src/pages/index.tsx
  src/pages/login/index.tsx
  src/pages/mydashboard/index.tsx
  src/pages/mypage/index.tsx
  src/pages/signup/index.tsx
Labels: feat

#26 fix: 가변 다이나믹 서브셋 버전으로 교체, 전역 적용
  src/styles/globals.css
  tailwind.config.ts
Labels: fix

#32 feat: /auth, /card api 제작
  package-lock.json
  package.json
  src/constants/types.ts
  src/lib/api.ts
  src/lib/axios.ts
Labels: feat

#35 Feat/sozign/21
  Public/assets/eye_off.svg
  Public/assets/eye_on.svg
  src/components/common/Input/AuthInput.tsx
  src/components/common/Input/ErrorMessage.tsx
  src/components/common/Input/FormInput.tsx
  src/components/modal/Layout.tsx
  src/constants/validation.ts
  src/pages/dashboard/[boardid]/index.tsx
  src/pages/login/index.tsx
Labels: feat

#42 feat: DatePicker 라이브러리 + react-hook-form
  Public/assets/calender.svg
  package-lock.json
  package.json
  src/components/common/Input/FormInput.tsx
  src/pages/dashboard/[boardid]/index.tsx
Labels: feat

#49 feat: 사이드바 포함한 PageLayout 컴포넌트 제작
  Public/assets/checked.svg
  src/components/common/PageLayout.tsx
  src/components/common/SideBar.tsx
  src/constants/mock.json
  src/pages/dashboard/[boardid]/index.tsx
Labels: feat

#60 feat: mydashboard 페이지 ui 제작(대시보드 추가, 대시보드 리스트), Auth 버튼수정
  Public/assets/addIcon.svg
  Public/assets/arrowIcon.svg
  Public/assets/chip/purpleChip.png
  Public/assets/notInvited.svg
  src/components/common/Buttons/AddButton.tsx
  src/components/common/Buttons/AuthButton.tsx
  src/components/common/Buttons/Button.tsx
  src/components/common/chips/ColorChip.tsx
  src/components/common/chips/SquareChip.tsx
  src/components/domains/myDashBoard/DashboardButton.tsx
  src/components/domains/myDashBoard/NotInvited.tsx
  src/components/domains/myDashBoard/PaginationButton.tsx
  src/components/domains/myDashBoard/addDashboardModal.tsx
  src/pages/mydashboard/index.tsx
Labels: feat

#66 feat: TagInput 제작 및 FormInput 수정
  src/components/common/Input/FormInput.tsx
  src/components/common/Input/TagInput.tsx
  src/components/common/SideBar.tsx
  src/components/common/chips/TagChip.tsx
  src/pages/dashboard/[boardid]/index.tsx
  src/utils/stringToColor.ts
Labels: feat

#67 Feat/hyun522/58
  src/components/common/chips/StatusChip.tsx
  src/components/dropdown/DropDownManager.tsx
  src/components/dropdown/DropDownProgress.tsx
  src/components/dropdown/mockData.ts
Labels: feat

#72 design: PageLayout의 Sidebar fixed position으로 수정
  src/components/common/PageLayout.tsx
Labels: design

#74 feat: /dashboard/[boardid] 페이지 레이아웃 제작
  Public/assets/bullet.svg
  src/components/common/Input/TagInput.tsx
  src/components/common/SideBar.tsx
  src/components/domains/dashboard/CardLayout.tsx
  src/components/domains/dashboard/Column.tsx
  src/components/domains/dashboard/TaskCard.tsx
  src/constants/mock.json
  src/lib/api.ts
  src/pages/dashboard/[boardid]/index.tsx
Labels: feat

#75 나의 대시보드 ui(초대 관련), 대시보드 생성 기능 일부 구현
  Public/assets/searchIcon.svg
  src/components/common/Buttons/addDashboardButton.tsx
  src/components/domains/myDashBoard/DashboardButton.tsx
  src/pages/mydashboard/index.tsx
Labels: feat

#78 feat:대시보드 리스트 조회 api 적용, 페이지네이션 기능 구현
  package-lock.json
  package.json
  src/components/domains/myDashBoard/DashboardButton.tsx
  src/components/domains/myDashBoard/InvitationList.tsx
  src/components/domains/myDashBoard/NotInvited.tsx
  src/components/domains/myDashBoard/PaginationButton.tsx
  src/constants/types.ts
  src/pages/mydashboard/index.tsx
Labels: feat

#82 feat: TagChip 배경색-글자색 랜덤하게 (네 개 중 하나)
  src/components/common/chips/TagChip.tsx
  src/utils/stringToColor.ts
Labels: feat

#84 fix : 로그인 성공시 페이지 이동 수정
  src/pages/login/index.tsx
Labels: fix
