Repository sozign/codeit-top-secret-X, pull requests merged in 2024-02, with the labels that each got.

#86 feat:대시보드 버튼 클릭시 페이지 이동 구현 ,초대부분 ui완성(+반응형)
  src/components/domains/myDashBoard/DashboardButton.tsx
  src/components/domains/myDashBoard/InvitationList.tsx
  src/pages/mydashboard/index.tsx
Labels: feat

#88 feat: /dashboard/[boardid] 컬럼별 무한 스크롤 구현
  src/components/domains/dashboard/Column.tsx
Labels: feat

#91 feat: 할 일 생성 모달 제작
  next.config.mjs
  src/components/common/Input/TagInput.tsx
  src/components/domains/dashboard/Column.tsx
  src/components/domains/dashboard/TaskCard.tsx
  src/components/dropdown/DropDownManager.tsx
  src/constants/types.ts
  src/lib/api.ts
  src/lib/axios.ts
  src/utils/stringToColor.ts
Labels: feat

#92 feat: edit 페이지 구현
  Public/assets/NotInvited.svg
  Public/assets/addBox.svg
  Public/assets/arrowForward.svg
  Public/assets/arrowLeft.svg
  Public/assets/arrowRight.svg
  src/components/common/Buttons/Button.tsx
  src/components/common/Headers/DashboardHeader.tsx
  src/components/common/Headers/MyDashboardHeader.tsx
  src/components/common/chips/ColorPick.tsx
  src/components/domains/edit/EditBox.tsx
  src/components/domains/edit/EditPaginationButton.tsx
  src/components/domains/edit/Invitation.tsx
  src/components/domains/edit/InvitationsBox.tsx
  src/components/domains/edit/Member.tsx
  src/components/domains/edit/MemberBox.tsx
  src/components/modal/InviteModal.tsx
  src/constants/types.ts
  src/lib/api.ts
  src/pages/dashboard/[boardid]/edit.tsx
  src/pages/dashboard/[boardid]/index.tsx
  tailwind.config.ts
Labels: feat

#95 design: taskcard 이미지 추가
  next.config.mjs
  src/components/common/chips/TagChip.tsx
  src/components/domains/dashboard/CardLayout.tsx
  src/components/domains/dashboard/TaskCard.tsx
Labels: design

#90 fix : 헤더 컴포넌트 수정
  src/components/common/Headers/DashboardHeader.tsx
  src/components/common/Headers/HeaderNavDropdown.tsx
  src/components/common/Headers/LandingHeader.tsx
  src/components/common/Headers/MyDashboardHeader.tsx
  src/pages/dashboard/[boardid]/edit.tsx
  src/pages/dashboard/[boardid]/index.tsx
  src/pages/mydashboard/index.tsx
  src/pages/mypage/index.tsx
  src/pages/signup/index.tsx
  tailwind.config.ts
Labels: feat, fix, refactor, style

#102 feat: 아바타 컴포넌트 제작
  src/components/common/Avatar.tsx
  src/components/common/chips/TagChip.tsx
  src/components/domains/dashboard/TaskCard.tsx
  src/styles/globals.css
  src/utils/stringToNumber.ts
  tailwind.config.ts
Labels: feat

#105 design: 페이지 레이아웃 수정 (헤더, 사이드바)
  src/components/common/Headers/DashboardHeader.tsx
  src/components/common/PageLayout.tsx
  src/pages/dashboard/[boardid]/index.tsx
  src/pages/mydashboard/index.tsx
Labels: design

#109 Feat/hyun522/69
  Public/assets/myPage-leftArrow.svg
  Public/assets/myPage-plusIcon.svg
  src/components/modal/MyPagePassWordModal.tsx
  src/components/modal/MyPageProfileModal.tsx
  src/components/myPage/PassWordForm.tsx
  src/components/myPage/UploadImg.tsx
  src/constants/validation.ts
  src/lib/api.ts
  src/pages/mypage/index.tsx
Labels: feat

#107 feat: 초대 api 렌더링 관련 코드 수정, ui 수정
  src/components/common/Buttons/addDashboardButton.tsx
  src/components/common/chips/SquareChip.tsx
  src/components/domains/edit/InvitationsBox.tsx
  src/components/domains/myDashBoard/Invitation.tsx
  src/components/domains/myDashBoard/InvitationList.tsx
  src/components/domains/myDashBoard/NotInvited.tsx
  src/pages/mydashboard/index.tsx
Labels: feat, fix, design

#110 feat: 할 일 카드 모달 제작
  Public/assets/kebab.png
  src/components/common/chips/StatusChip.tsx
  src/components/domains/dashboard/Column.tsx
  src/components/domains/dashboard/TaskCard.tsx
  src/components/modal/Layout.tsx
  src/components/modal/TaskModal.tsx
  src/constants/types.ts
  src/lib/api.ts
  src/styles/globals.css
Labels: feat

#114 Feat/hyun522/112
  src/components/common/Input/PasswordInput.tsx
  src/components/modal/MyPagePassWordModal.tsx
  src/components/myPage/PassWordForm.tsx
  src/components/myPage/UploadImg.tsx
  src/pages/mypage/index.tsx
Labels: feat

#115 feat: Landing Page, 404 Page 구현
  Public/assets/email.svg
  Public/assets/facebook.svg
  Public/assets/instagram.svg
  Public/assets/logo.svg
  Public/assets/logoTitle.svg
  Public/images/landing1.png
  Public/images/landing2.png
  Public/images/landing3.png
  Public/images/landing4.png
  Public/images/landing5.png
  Public/images/notFound.png
  Public/images/people.png
  src/components/domains/edit/InvitationsBox.tsx
  src/pages/404.tsx
  src/pages/dashboard/[boardid]/edit.tsx
  src/pages/index.tsx
  tailwind.config.ts
Labels: feat

#120 feat: '할 일 생성'모달 스타일 개선 및 리팩토링
  Public/assets/editPencil.svg
  src/components/common/Input/TagInput.tsx
  src/components/domains/dashboard/Column.tsx
  src/components/dropdown/DropDownManager.tsx
  src/components/modal/AddNewTaskModal.tsx
  src/constants/types.ts
Labels: feat, refactor

#128 feat : 대시보드 헤더 구현
  src/components/common/Avatar.tsx
  src/components/common/Headers/DashboardHeader.tsx
  src/components/common/Headers/LandingHeader.tsx
  src/pages/mypage/index.tsx
  tailwind.config.ts
Labels: feat, design

#129 fix: 폰트 적용 이슈 해결
  src/components/common/Avatar.tsx
  src/styles/font.js
  src/styles/globals.css
Labels: fix

#131 fix : 프로필 이미지 에러 해결
  src/components/common/Headers/DashboardHeader.tsx
  tailwind.config.ts
Labels: fix, design

#132 fix: 이미지 깨짐 버그 수정
  next.config.mjs
Labels: fix

#135 feat:초대 관련 중복 식별기능 추가
  src/components/domains/myDashBoard/Invitation.tsx
  src/components/domains/myDashBoard/InvitationList.tsx
  src/lib/api.ts
  src/pages/mydashboard/index.tsx
Labels: feat

#141 Feat: 컬럼 추가 모현
  src/components/domains/dashboard/AddColumnButton.tsx
  src/components/modal/AddColumnModal.tsx
  src/pages/dashboard/[boardid]/index.tsx
Labels: feat

#143 feat : 컬럼 수정 모달창 구현
  src/components/common/Headers/DashboardHeader.tsx
  src/components/domains/dashboard/Column.tsx
  src/components/modal/ColumnsDeletedModal.tsx
  src/components/modal/ColumnsEditModal.tsx
Labels: feat

#147 refactor: column, member 데이터 context로 전역 사용 가능하게
  src/components/common/Headers/DashboardHeader.tsx
  src/components/domains/dashboard/Column.tsx
  src/components/modal/AddColumnModal.tsx
  src/components/modal/ColumnsDeletedModal.tsx
  src/components/modal/TaskEditModal.tsx
  src/context/DashboardContext.tsx
  src/pages/_app.tsx
  src/pages/dashboard/[boardid]/index.tsx
Labels: refactor

#149 Feat/pjw980921/146
  package-lock.json
  package.json
  src/components/common/Headers/DashboardHeader.tsx
  src/components/domains/myDashBoard/InvitationList.tsx
Labels: feat

#154 design: 할일생성/수정 모달 모바일대응
  src/components/common/Input/ErrorMessage.tsx
  src/components/common/Input/FormInput.tsx
  src/components/common/Input/TagInput.tsx
  src/components/dropdown/DropDownManager.tsx
  src/components/dropdown/DropDownProgress.tsx
  src/components/modal/AddNewTaskModal.tsx
  src/components/modal/Layout.tsx
  src/components/modal/TaskEditModal.tsx
Labels: design

#156 Style/pjw980921/153
  src/components/common/Headers/DashboardHeader.tsx
Labels: design

#165 feat : 랜딩페이지 유저프로필 구현
  src/components/common/Headers/HeaderNavDropdown.tsx
  src/components/common/Headers/LandingHeader.tsx
  src/pages/index.tsx
  src/pages/login/index.tsx
  src/pages/signup/index.tsx
Labels: feat

#166 Feat: z-index 추가 및 ConfirmModal (삭제 확인 모달) 구현
  src/components/common/Headers/DashboardHeader.tsx
  src/components/common/Headers/LandingHeader.tsx
  src/components/domains/edit/Invitation.tsx
  src/components/domains/edit/InvitationsBox.tsx
  src/components/domains/edit/Member.tsx
  src/components/modal/ColumnsEditModal.tsx
  src/components/modal/ConfirmModal.tsx
  src/components/modal/Layout.tsx
  src/components/modal/TaskModal.tsx
  src/pages/dashboard/[boardid]/edit.tsx
  tailwind.config.ts
Labels: feat

#169 feat: 댓글 수정/삭제 기능 추가
  src/components/common/Headers/DashboardHeader.tsx
  src/components/domains/dashboard/Comment.tsx
  src/components/modal/ConfirmModal.tsx
  src/components/modal/TaskModal.tsx
  src/context/UserContext.tsx
  src/lib/api.ts
  src/pages/_app.tsx
  src/pages/dashboard/[boardid]/edit.tsx
  src/pages/dashboard/[boardid]/index.tsx
Labels: feat

#180 fix: /mydashboard에서도 userInfo 로드
  src/components/modal/AddColumnModal.tsx
  src/pages/mydashboard/index.tsx
Labels: fix

#191 feat: userInfo 컨텍스트 헤더에서 지정
  src/components/common/Headers/DashboardHeader.tsx
  src/pages/dashboard/[boardid]/index.tsx
  src/pages/mydashboard/index.tsx
Labels: fix

#195 docs: /mydashboard, /dashboard/[id]페이지 시연 gif 추가
  README.md
Labels: docs

#196 feta:중복기능 제거, 입력창 디바운스 구현
  src/components/common/SideBar.tsx
  src/components/common/SideBarPagination.tsx
  src/components/domains/myDashBoard/InvitationList.tsx
  src/pages/mydashboard/index.tsx
Labels: feat

#200 feat: edit 페이지 에러 처리 및 수정
  src/components/common/Headers/HeaderNavDropdown.tsx
  src/components/domains/dashboard/Comment.tsx
  src/components/domains/edit/EditBox.tsx
  src/components/domains/edit/Invitation.tsx
  src/components/domains/edit/InvitationsBox.tsx
  src/components/domains/edit/Member.tsx
  src/components/domains/edit/MemberBox.tsx
  src/components/modal/ConfirmModal.tsx
  src/components/modal/InviteModal.tsx
  src/components/modal/Layout.tsx
  src/components/modal/TaskModal.tsx
  src/pages/dashboard/[boardid]/edit.tsx
  src/pages/dashboard/[boardid]/index.tsx
  tailwind.config.ts
Labels: feat, fix, design, refactor

#212 FIX : 모달창 텍스트 위치 수정
  src/components/modal/MyPageConfirmModal.tsx
Labels: fix

#215 FIX : header 프로필 이미지 반영 버그 해결
  src/components/myPage/UploadImg.tsx
Labels: fix

#239 Docs: Update README.md
  README.md
Labels: docs

#244 design: 모달 layout height 너무 길어지지 않게 수정
  src/components/modal/Layout.tsx
Labels: design, refactor
